### ISSUE TITLE
feature/input-error-detection

### ISSUE THREAD

**Issue by lbowes** [lbowes/scheduling-assistant#15]
### Description
There are ways that the user can provide invalid input to the application. These should be caught and reported.

### TODO
Catch and report the following errors:
Description input:
- [x] Duplicate attribute tags
- [x] Unrecognised tags

Logical errors in generated activity output:
- [x] Cyclical inheritance graph (check what happens when this is provided as input)
- [x] Unsatisfiable `min_session_length` given the set of `happens` windows (all to short)
- [x] `min_session_length` > `max_session_length`
