### ISSUE TITLE
feature/decouple-time-filling

### ISSUE THREAD

**Issue by lbowes** [lbowes/scheduling-assistant#54]
### Description
There should be an interface between the functionality to fill free time and the rest of the application. The user should provide as input:

* a window of time (start and end `datetime`s)
* a block length
* a string containing activity descriptions

At the moment, this functionality is not isolated - the `fill_free_time` script contains contains other logic

### TODO
- [x] Rename everything that references `keep to calendar` to `scheduling assistant` (better project name)
- [x] Rename `fill_free_time.py` to `fill_time_window.py`
- [ ] Change `fill_time_window.py` so it cannot be run as a standalone script (it would never make sense to do this, this functionality should be used by higher level modules)
- [x] Rename the function `fill_free_time` to `fill_time_window`
- [x] Change the input to this function so the third argument is a list of `ActivityDesc` objects, and not a file path string
- [x] Move the activity loading from file into a separate module
