### ISSUE TITLE
feature/context-generation

### ISSUE THREAD

**Issue by lbowes** [lbowes/scheduling-assistant#61]
### Description
In order to generate new events on a calendar, this app needs access to some context. The context should provide information relevant to the generation algorithm such as:

* the time block length
* the window of time being generated
* relevant information about existing calendar events (TBD)

The generation algorithm then takes this context as input.

### TODO
- [x] Create a new file `context_generation.py`
- [x] Create a new function in this file called `generate_context`
- [x] The function above should take as input the time block length and generation time window
- [ ] The function above should produce as output one `json` file containing whatever information is deemed necessary for the generation algorithm

**Comment by lbowes** [comment]
Output is a dictionary.
