### ISSUE TITLE
feature/google-calendar-integration

### ISSUE THREAD

**Issue by lbowes** [lbowes/scheduling-assistant#63]
### Description
It should be possible to add generated events to Google Calendar. The ability to extract information from existing events on Google Calendar will be part of more detailed context generation in future.

### TODO
- [x] Get the [Google Calendar Simple API](https://github.com/kuzmoyev/google-calendar-simple-api) working
- [x] `fill_time_window` should add one event to Google Calendar in the window specified
- [x] `generate_context` should output a dictionary containing the length of the most recent event before the input time window (the simplest way to test that it is possible to get information from a calendar)
