### ISSUE TITLE
feature/cal-event-listener

### ISSUE THREAD

**Issue by lbowes** [lbowes/scheduling-assistant#67]
### Description
The app should run from a single python script and listen for updates (events added/updated/removed) to a Google Calendar. The intent of the user should be extracted from the updates, and this can be used to generate new events. Different options are given in #44.

### TODO
- [x] Create a new python file to serve as the single point of entry for the app
- [x] In the file above, set up the main event listener connected to Pipedream
- [ ] If an event is created with the title `generate` then run `fill_time_window` within the time covered by the event just added, before deleting the original event
- [ ] Add a code coverage workflow file
