### ISSUE TITLE
feature/scheduling-algorithm

### ISSUE THREAD

**Issue by lbowes** [lbowes/scheduling-assistant#69]
### Description
The scheduling algorithm at the core of this application needs to be created. Infrastructure around the algorithm has been completed.

**Input:**
* window of time
* a set of activity descriptions

**Output:**
* a set of events 

There are a number of ways this could be done. The aim of this is to explore different options:

1. Come up with a scoring function for a given period of time, and use a genetic algorithm to optimise over this.
2. Manually write bin-packing rules for fitting events within the input time window
3. Random search (probably won't be used in practice, but interesting to see what quality this approach could provide)

A significant portion of this work can/should be done on paper.

**Considerations**
1. With only the maximum length of an event provided as input, what should the default length of an event be? What is the balance between making events as small as possible vs making them as long as possible? Context switching penalty?
2. Could the event length for a given activity be learned based on a rolling average of previous events (starting with e.g. 2 hours if no existing data is available)
3. Based on answer to Q1, are there any other attributes that activity descriptions should have?
    * Similarity graph?
    * Target time allocation percentage?
    * Relative priorities?

### TODO
- [ ] Given the current attributes of an activity, come up with a scoring function for a set of events
- [ ] Create a random generation policy (continuously select events until they fit within the remaining time window)
- [ ] For each policy, visualise the results with the [event plotter](https://github.com/lbowes/event-plotter)
