### ISSUE TITLE
toggl-api-integration

### ISSUE THREAD

**Issue by lbowes** [lbowes/scheduling-assistant#7]
### Description
Toggl should be used for time tracking. Use their [public API](https://github.com/toggl/toggl_api_docs/blob/master/toggl_api.md) to extract time entries and populate a file describing the current time allocation for different projects (see #6).

### Tasks
- [x] Read documentation on Toggl API
- [x] Access time entries
- [x] Combine results into allocation
